AWSTemplateFormatVersion: 2010-09-09
Description: 'Lambda function for simple calculator'


Resources:
  lambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - s3.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: policyname
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Resource: "*"
            Action:
            - logs:CreateLogStream
            - logs:DescribeLogGroup
            - logs:PutLogEvents
            
  
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
            # TODO implement
            def sum(a, b):
              return a + b
            def difference(a, b):
              return a - b
            def product(a, b):
              return a * b
            a=5
            b=2
            print(sum(a,b))
            print(difference(a,b))
            print(product(a,b))
      FunctionName: calculator_lambda_function
      Handler: index.lambda_handler
      Role: !GetAtt lambdaRole.Arn
      Runtime: python3.7
      




                